name: generate snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Annaxs
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#2EF9B6&color_dots=#0A0F1E,#4A1030,#8C1960,#CC3AA8,#FF4FD8

      - uses: crazy-max/ghaction-github-pages@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: output
          build_dir: dist
